import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: "class",
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,jsx,ts,tsx}',
    './node_modules/tailwind-datepicker-react/dist/**/*.js', // <--- Add this line
  ],
  safelist: [
    'hidden',
    'border-blue-400',
    'border-gray-400',
    'border-green-400',
    'border-orange-400',
    'border-red-400',
    'border-sky-400',
    'checked:text-blue-400',
    'checked:text-blue-700',
    'checked:text-gray-400',
    'checked:text-gray-700',
    'checked:text-green-400',
    'checked:text-green-700',
    'checked:text-orange-400',
    'checked:text-orange-700',
    'checked:text-red-400',
    'checked:text-red-700',
    'checked:text-sky-400',
    'checked:text-sky-700',
    'dark:text-blue-200',
    'dark:text-blue-700',
    'dark:text-gray-200',
    'dark:text-gray-700',
    'dark:text-green-200',
    'dark:text-green-700',
    'dark:text-orange-200',
    'dark:bg-orange-300',
    'dark:bg-blue-300',
    'dark:bg-gray-300',
    'dark:bg-green-300',
    'dark:bg-orange-300',
    'text-red-200',
    'text-red-700',
    'text-sky-200',
    'text-sky-700',
    'bg-red-100',
    'bg-orange-100',
    'bg-green-100',
    'bg-blue-100',
    'bg-sky-100',
    'bg-gray-100',
    'bg-gray-300',
    'bg-gray-200',
    'hover:bg-gray-100',
    'hover:bg-gray-300',
    'hover:bg-gray-200',
    'dark:hover:bg-gray-300',
    'dark:hover:bg-gray-400',
    'dark:hover:bg-gray-500',
    'dark:hover:bg-gray-600',
  ],
  theme: {
    extend: {
      colors: {
        'dark-header': '#1f2327',
        'light-header': '#fbfbfa',
      },
    },
  },
  plugins: [require('daisyui'), require("@tailwindcss/forms")({
  themes: ["light", "dark"],
    strategy: 'class', // only generate classes don't add opinions
  })],
};
export default config;
