import Header from '@/src/lib/components/header';
import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

const inter = Inter({
  weight: ['300', '700'],
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className={`${inter.className} flex-col flex h-full w-full`}>
      <header className=''>
        <Header />
      </header>
        {children}
      <footer className='h-32 min-h-[8rem]' />
    </body>
  );
}
